package main.java.com.propco.rts.server.pojo.v1;
// Generated 17-May-2017 12:47:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Housekeeping generated by hbm2java
 */
@Entity
@Table(name="housekeeping"
    ,catalog="PROPCO_Maven_new"
)
public class Housekeeping  implements java.io.Serializable {


     private String hktype;
     private String description;

    public Housekeeping() {
    }

    public Housekeeping(String hktype, String description) {
       this.hktype = hktype;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="HKType", unique=true, nullable=false)
    public String getHktype() {
        return this.hktype;
    }
    
    public void setHktype(String hktype) {
        this.hktype = hktype;
    }

    
    @Column(name="Description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


