package com.propco.rts.pojo.v1;
// Generated 21-May-2017 12:09:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private int activityId;
	private ServiceRequest serviceRequest;
	private String location;
	private String notes;
	private String status;
	private Date creationDateTime;
	private Date updateDateTime;
	private String updatedByUser;

	public Activity() {
	}

	public Activity(int activityId, ServiceRequest serviceRequest) {
		this.activityId = activityId;
		this.serviceRequest = serviceRequest;
	}

	public Activity(int activityId, ServiceRequest serviceRequest, String location, String notes, String status,
			Date creationDateTime, Date updateDateTime, String updatedByUser) {
		this.activityId = activityId;
		this.serviceRequest = serviceRequest;
		this.location = location;
		this.notes = notes;
		this.status = status;
		this.creationDateTime = creationDateTime;
		this.updateDateTime = updateDateTime;
		this.updatedByUser = updatedByUser;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public ServiceRequest getServiceRequest() {
		return this.serviceRequest;
	}

	public void setServiceRequest(ServiceRequest serviceRequest) {
		this.serviceRequest = serviceRequest;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreationDateTime() {
		return this.creationDateTime;
	}

	public void setCreationDateTime(Date creationDateTime) {
		this.creationDateTime = creationDateTime;
	}

	public Date getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(Date updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
