package com.propco.rts.pojo.v1;
// Generated 22-May-2017 8:46:33 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Bundle generated by hbm2java
 */
public class Bundle implements java.io.Serializable {

	private Integer bundleId;
	private String bundleName;
	private Set customers = new HashSet(0);

	public Bundle() {
	}

	public Bundle(String bundleName) {
		this.bundleName = bundleName;
	}

	public Bundle(String bundleName, Set customers) {
		this.bundleName = bundleName;
		this.customers = customers;
	}

	public Integer getBundleId() {
		return this.bundleId;
	}

	public void setBundleId(Integer bundleId) {
		this.bundleId = bundleId;
	}

	public String getBundleName() {
		return this.bundleName;
	}

	public void setBundleName(String bundleName) {
		this.bundleName = bundleName;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

}
