package com.propco.rts.pojo.v1;
// Generated 21-May-2017 12:09:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int customerId;
	private Billing billing;
	private Bundle bundle;
	private String customerName;
	private String notes;
	private String address;
	private String addressNotes;
	private String city;
	private String province;
	private String postalCode;
	private String contactName;
	private String primaryPhone;
	private String ext;
	private String secondaryPhone;
	private String ext2;
	private String other;
	private String fax;
	private String emailAddress;
	private Date creationDate;
	private Date updateDate;
	private byte updatedByUser;
	private Set serviceRequests = new HashSet(0);

	public Customer() {
	}

	public Customer(int customerId, Billing billing, Bundle bundle, String customerName, String address, String city,
			String province, String postalCode, String contactName, String primaryPhone, String ext, Date creationDate,
			Date updateDate, byte updatedByUser) {
		this.customerId = customerId;
		this.billing = billing;
		this.bundle = bundle;
		this.customerName = customerName;
		this.address = address;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.contactName = contactName;
		this.primaryPhone = primaryPhone;
		this.ext = ext;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.updatedByUser = updatedByUser;
	}

	public Customer(int customerId, Billing billing, Bundle bundle, String customerName, String notes, String address,
			String addressNotes, String city, String province, String postalCode, String contactName,
			String primaryPhone, String ext, String secondaryPhone, String ext2, String other, String fax,
			String emailAddress, Date creationDate, Date updateDate, byte updatedByUser, Set serviceRequests) {
		this.customerId = customerId;
		this.billing = billing;
		this.bundle = bundle;
		this.customerName = customerName;
		this.notes = notes;
		this.address = address;
		this.addressNotes = addressNotes;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.contactName = contactName;
		this.primaryPhone = primaryPhone;
		this.ext = ext;
		this.secondaryPhone = secondaryPhone;
		this.ext2 = ext2;
		this.other = other;
		this.fax = fax;
		this.emailAddress = emailAddress;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.updatedByUser = updatedByUser;
		this.serviceRequests = serviceRequests;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public Billing getBilling() {
		return this.billing;
	}

	public void setBilling(Billing billing) {
		this.billing = billing;
	}

	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddressNotes() {
		return this.addressNotes;
	}

	public void setAddressNotes(String addressNotes) {
		this.addressNotes = addressNotes;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getPrimaryPhone() {
		return this.primaryPhone;
	}

	public void setPrimaryPhone(String primaryPhone) {
		this.primaryPhone = primaryPhone;
	}

	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public String getSecondaryPhone() {
		return this.secondaryPhone;
	}

	public void setSecondaryPhone(String secondaryPhone) {
		this.secondaryPhone = secondaryPhone;
	}

	public String getExt2() {
		return this.ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public byte getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(byte updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

	public Set getServiceRequests() {
		return this.serviceRequests;
	}

	public void setServiceRequests(Set serviceRequests) {
		this.serviceRequests = serviceRequests;
	}

}
