package com.propco.rts.pojo.v1;
// Generated 21-May-2017 12:09:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private int departmentId;
	private Billing billing;
	private String departmentName;
	private String contractNr;
	private Date creationDate;
	private Date updateDate;
	private byte updatedByUser;

	public Department() {
	}

	public Department(int departmentId, Billing billing, String departmentName, String contractNr, Date creationDate,
			Date updateDate, byte updatedByUser) {
		this.departmentId = departmentId;
		this.billing = billing;
		this.departmentName = departmentName;
		this.contractNr = contractNr;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.updatedByUser = updatedByUser;
	}

	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public Billing getBilling() {
		return this.billing;
	}

	public void setBilling(Billing billing) {
		this.billing = billing;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getContractNr() {
		return this.contractNr;
	}

	public void setContractNr(String contractNr) {
		this.contractNr = contractNr;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public byte getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(byte updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

}
