package com.propco.rts.pojo.v1;
// Generated 22-May-2017 8:46:33 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceRequest generated by hbm2java
 */
public class ServiceRequest implements java.io.Serializable {

	private Integer serviceRequestId;
	private Customer customer;
	private String purchaseOrderNumber;
	private String invoiceFrequency;
	private String serviceType;
	private String paymentType;
	private String schedule;
	private Date serviceDate;
	private Date creationDate;
	private Date updateDate;
	private String updatedByUser;
	private Set activities = new HashSet(0);

	public ServiceRequest() {
	}

	public ServiceRequest(Customer customer, String invoiceFrequency, String serviceType, String paymentType,
			String schedule, Date serviceDate, Date creationDate, Date updateDate, String updatedByUser) {
		this.customer = customer;
		this.invoiceFrequency = invoiceFrequency;
		this.serviceType = serviceType;
		this.paymentType = paymentType;
		this.schedule = schedule;
		this.serviceDate = serviceDate;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.updatedByUser = updatedByUser;
	}

	public ServiceRequest(Customer customer, String purchaseOrderNumber, String invoiceFrequency, String serviceType,
			String paymentType, String schedule, Date serviceDate, Date creationDate, Date updateDate,
			String updatedByUser, Set activities) {
		this.customer = customer;
		this.purchaseOrderNumber = purchaseOrderNumber;
		this.invoiceFrequency = invoiceFrequency;
		this.serviceType = serviceType;
		this.paymentType = paymentType;
		this.schedule = schedule;
		this.serviceDate = serviceDate;
		this.creationDate = creationDate;
		this.updateDate = updateDate;
		this.updatedByUser = updatedByUser;
		this.activities = activities;
	}

	public Integer getServiceRequestId() {
		return this.serviceRequestId;
	}

	public void setServiceRequestId(Integer serviceRequestId) {
		this.serviceRequestId = serviceRequestId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getPurchaseOrderNumber() {
		return this.purchaseOrderNumber;
	}

	public void setPurchaseOrderNumber(String purchaseOrderNumber) {
		this.purchaseOrderNumber = purchaseOrderNumber;
	}

	public String getInvoiceFrequency() {
		return this.invoiceFrequency;
	}

	public void setInvoiceFrequency(String invoiceFrequency) {
		this.invoiceFrequency = invoiceFrequency;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	public Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdatedByUser() {
		return this.updatedByUser;
	}

	public void setUpdatedByUser(String updatedByUser) {
		this.updatedByUser = updatedByUser;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

}
