package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Billing generated by hbm2java
 */
public class Billing  implements java.io.Serializable {


     private Integer billingId;
     private String billingName;
     private String billingAlias;
     private String billingAddress;
     private String billingCity;
     private String billingProvince;
     private String billingPostalCode;
     private String billingContactName;
     private String billingPrimaryPhone;
     private String billingExt;
     private String billingSecondaryPhone;
     private String billingExt2;
     private String billingFax;
     private String billingEmailAddress;
     private String tax;
     private String taxRate;
     private Date creationDate;
     private Date updateDate;
     private int updatedByUser;
     private Set customers = new HashSet(0);
     private Set departments = new HashSet(0);

    public Billing() {
    }

	
    public Billing(String billingName, String billingAddress, String billingCity, String billingPrimaryPhone, String tax, String taxRate, Date creationDate, Date updateDate, int updatedByUser) {
        this.billingName = billingName;
        this.billingAddress = billingAddress;
        this.billingCity = billingCity;
        this.billingPrimaryPhone = billingPrimaryPhone;
        this.tax = tax;
        this.taxRate = taxRate;
        this.creationDate = creationDate;
        this.updateDate = updateDate;
        this.updatedByUser = updatedByUser;
    }
    public Billing(String billingName, String billingAlias, String billingAddress, String billingCity, String billingProvince, String billingPostalCode, String billingContactName, String billingPrimaryPhone, String billingExt, String billingSecondaryPhone, String billingExt2, String billingFax, String billingEmailAddress, String tax, String taxRate, Date creationDate, Date updateDate, int updatedByUser, Set customers, Set departments) {
       this.billingName = billingName;
       this.billingAlias = billingAlias;
       this.billingAddress = billingAddress;
       this.billingCity = billingCity;
       this.billingProvince = billingProvince;
       this.billingPostalCode = billingPostalCode;
       this.billingContactName = billingContactName;
       this.billingPrimaryPhone = billingPrimaryPhone;
       this.billingExt = billingExt;
       this.billingSecondaryPhone = billingSecondaryPhone;
       this.billingExt2 = billingExt2;
       this.billingFax = billingFax;
       this.billingEmailAddress = billingEmailAddress;
       this.tax = tax;
       this.taxRate = taxRate;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.updatedByUser = updatedByUser;
       this.customers = customers;
       this.departments = departments;
    }
   
    public Integer getBillingId() {
        return this.billingId;
    }
    
    public void setBillingId(Integer billingId) {
        this.billingId = billingId;
    }
    public String getBillingName() {
        return this.billingName;
    }
    
    public void setBillingName(String billingName) {
        this.billingName = billingName;
    }
    public String getBillingAlias() {
        return this.billingAlias;
    }
    
    public void setBillingAlias(String billingAlias) {
        this.billingAlias = billingAlias;
    }
    public String getBillingAddress() {
        return this.billingAddress;
    }
    
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress;
    }
    public String getBillingCity() {
        return this.billingCity;
    }
    
    public void setBillingCity(String billingCity) {
        this.billingCity = billingCity;
    }
    public String getBillingProvince() {
        return this.billingProvince;
    }
    
    public void setBillingProvince(String billingProvince) {
        this.billingProvince = billingProvince;
    }
    public String getBillingPostalCode() {
        return this.billingPostalCode;
    }
    
    public void setBillingPostalCode(String billingPostalCode) {
        this.billingPostalCode = billingPostalCode;
    }
    public String getBillingContactName() {
        return this.billingContactName;
    }
    
    public void setBillingContactName(String billingContactName) {
        this.billingContactName = billingContactName;
    }
    public String getBillingPrimaryPhone() {
        return this.billingPrimaryPhone;
    }
    
    public void setBillingPrimaryPhone(String billingPrimaryPhone) {
        this.billingPrimaryPhone = billingPrimaryPhone;
    }
    public String getBillingExt() {
        return this.billingExt;
    }
    
    public void setBillingExt(String billingExt) {
        this.billingExt = billingExt;
    }
    public String getBillingSecondaryPhone() {
        return this.billingSecondaryPhone;
    }
    
    public void setBillingSecondaryPhone(String billingSecondaryPhone) {
        this.billingSecondaryPhone = billingSecondaryPhone;
    }
    public String getBillingExt2() {
        return this.billingExt2;
    }
    
    public void setBillingExt2(String billingExt2) {
        this.billingExt2 = billingExt2;
    }
    public String getBillingFax() {
        return this.billingFax;
    }
    
    public void setBillingFax(String billingFax) {
        this.billingFax = billingFax;
    }
    public String getBillingEmailAddress() {
        return this.billingEmailAddress;
    }
    
    public void setBillingEmailAddress(String billingEmailAddress) {
        this.billingEmailAddress = billingEmailAddress;
    }
    public String getTax() {
        return this.tax;
    }
    
    public void setTax(String tax) {
        this.tax = tax;
    }
    public String getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public int getUpdatedByUser() {
        return this.updatedByUser;
    }
    
    public void setUpdatedByUser(int updatedByUser) {
        this.updatedByUser = updatedByUser;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }




}


