package com.mycompany.propco_maven_new;
// Generated 17-May-2017 12:47:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bundles generated by hbm2java
 */
@Entity
@Table(name="bundles"
    ,catalog="PROPCO_Maven_new"
)
public class Bundles  implements java.io.Serializable {


     private int bundleId;
     private String bundleName;
     private Set customers = new HashSet(0);

    public Bundles() {
    }

	
    public Bundles(int bundleId, String bundleName) {
        this.bundleId = bundleId;
        this.bundleName = bundleName;
    }
    public Bundles(int bundleId, String bundleName, Set customers) {
       this.bundleId = bundleId;
       this.bundleName = bundleName;
       this.customers = customers;
    }
   
     @Id 

    
    @Column(name="bundleID", unique=true, nullable=false)
    public int getBundleId() {
        return this.bundleId;
    }
    
    public void setBundleId(int bundleId) {
        this.bundleId = bundleId;
    }

    
    @Column(name="bundleName", nullable=false, length=30)
    public String getBundleName() {
        return this.bundleName;
    }
    
    public void setBundleName(String bundleName) {
        this.bundleName = bundleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bundles")
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


