package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bundles generated by hbm2java
 */
public class Bundles  implements java.io.Serializable {


     private int bundleId;
     private String bundleName;
     private Set customers = new HashSet(0);

    public Bundles() {
    }

	
    public Bundles(int bundleId, String bundleName) {
        this.bundleId = bundleId;
        this.bundleName = bundleName;
    }
    public Bundles(int bundleId, String bundleName, Set customers) {
       this.bundleId = bundleId;
       this.bundleName = bundleName;
       this.customers = customers;
    }
   
    public int getBundleId() {
        return this.bundleId;
    }
    
    public void setBundleId(int bundleId) {
        this.bundleId = bundleId;
    }
    public String getBundleName() {
        return this.bundleName;
    }
    
    public void setBundleName(String bundleName) {
        this.bundleName = bundleName;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


