package com.mycompany.propco_maven_new;
// Generated 21-May-2017 5:38:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,catalog="PROPCO_Maven_new"
    , uniqueConstraints = @UniqueConstraint(columnNames="departmentName") 
)
public class Department  implements java.io.Serializable {


     private int departmentId;
     private Billing billing;
     private String departmentName;
     private String contractNumber;
     private Date creationDate;
     private Date updateDate;
     private int updatedByUser;

    public Department() {
    }

    public Department(int departmentId, Billing billing, String departmentName, String contractNumber, Date creationDate, Date updateDate, int updatedByUser) {
       this.departmentId = departmentId;
       this.billing = billing;
       this.departmentName = departmentName;
       this.contractNumber = contractNumber;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.updatedByUser = updatedByUser;
    }
   
     @Id

    
    @Column(name="departmentID", unique=true, nullable=false)
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="billingID", nullable=false)
    public Billing getBilling() {
        return this.billing;
    }
    
    public void setBilling(Billing billing) {
        this.billing = billing;
    }

    
    @Column(name="departmentName", unique=true, nullable=false, length=50)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="contractNumber", nullable=false, length=15)
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creationDate", nullable=false, length=0)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updateDate", nullable=false, length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="updatedByUser", nullable=false)
    public int getUpdatedByUser() {
        return this.updatedByUser;
    }
    
    public void setUpdatedByUser(int updatedByUser) {
        this.updatedByUser = updatedByUser;
    }




}


