package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private int departmentId;
     private Billing billing;
     private String departmentName;
     private String contractNumber;
     private Date creationDate;
     private Date updateDate;
     private int updatedByUser;

    public Department() {
    }

    public Department(int departmentId, Billing billing, String departmentName, String contractNumber, Date creationDate, Date updateDate, int updatedByUser) {
       this.departmentId = departmentId;
       this.billing = billing;
       this.departmentName = departmentName;
       this.contractNumber = contractNumber;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.updatedByUser = updatedByUser;
    }
   
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }
    public Billing getBilling() {
        return this.billing;
    }
    
    public void setBilling(Billing billing) {
        this.billing = billing;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public int getUpdatedByUser() {
        return this.updatedByUser;
    }
    
    public void setUpdatedByUser(int updatedByUser) {
        this.updatedByUser = updatedByUser;
    }




}


