package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1



/**
 * Housekeeping generated by hbm2java
 */
public class Housekeeping  implements java.io.Serializable {


     private String hktype;
     private String description;

    public Housekeeping() {
    }

    public Housekeeping(String hktype, String description) {
       this.hktype = hktype;
       this.description = description;
    }
   
    public String getHktype() {
        return this.hktype;
    }
    
    public void setHktype(String hktype) {
        this.hktype = hktype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


