package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1



/**
 * Pests generated by hbm2java
 */
public class Pests  implements java.io.Serializable {


     private int pestsId;
     private String pestsType;

    public Pests() {
    }

    public Pests(int pestsId, String pestsType) {
       this.pestsId = pestsId;
       this.pestsType = pestsType;
    }
   
    public int getPestsId() {
        return this.pestsId;
    }
    
    public void setPestsId(int pestsId) {
        this.pestsId = pestsId;
    }
    public String getPestsType() {
        return this.pestsType;
    }
    
    public void setPestsType(String pestsType) {
        this.pestsType = pestsType;
    }




}


