package com.mycompany.propco_maven_new;
// Generated 17-May-2017 12:47:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pests generated by hbm2java
 */
@Entity
@Table(name="pests"
    ,catalog="PROPCO_Maven_new"
)
public class Pests  implements java.io.Serializable {


     private int pestsId;
     private String pestsType;

    public Pests() {
    }

    public Pests(int pestsId, String pestsType) {
       this.pestsId = pestsId;
       this.pestsType = pestsType;
    }
   
     @Id 

    
    @Column(name="pestsID", unique=true, nullable=false)
    public int getPestsId() {
        return this.pestsId;
    }
    
    public void setPestsId(int pestsId) {
        this.pestsId = pestsId;
    }

    
    @Column(name="pestsType", nullable=false, length=30)
    public String getPestsType() {
        return this.pestsType;
    }
    
    public void setPestsType(String pestsType) {
        this.pestsType = pestsType;
    }




}


