package com.mycompany.propco_maven_new;
// Generated 21-May-2017 5:38:12 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="PROPCO_Maven_new"
)
public class Product  implements java.io.Serializable {


     private Byte id;
     private String productName;
     private String measurement;
     private String pcpnumber;

    public Product() {
    }

    public Product(String productName, String measurement, String pcpnumber) {
       this.productName = productName;
       this.measurement = measurement;
       this.pcpnumber = pcpnumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Byte getId() {
        return this.id;
    }
    
    public void setId(Byte id) {
        this.id = id;
    }

    
    @Column(name="ProductName", nullable=false, length=35)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="Measurement", nullable=false, length=8)
    public String getMeasurement() {
        return this.measurement;
    }
    
    public void setMeasurement(String measurement) {
        this.measurement = measurement;
    }

    
    @Column(name="PCPNumber", nullable=false, length=6)
    public String getPcpnumber() {
        return this.pcpnumber;
    }
    
    public void setPcpnumber(String pcpnumber) {
        this.pcpnumber = pcpnumber;
    }




}


