package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ServiceRequestActivities generated by hbm2java
 */
public class ServiceRequestActivities  implements java.io.Serializable {


     private int activityNr;
     private ServiceRequest serviceRequest;
     private String workOrderNr;
     private String unit;
     private String notes;
     private int pestsId;
     private String activityStatus;
     private Date creationDate;
     private Date updateDate;
     private int updatedByUser;

    public ServiceRequestActivities() {
    }

    public ServiceRequestActivities(int activityNr, ServiceRequest serviceRequest, String workOrderNr, String unit, String notes, int pestsId, String activityStatus, Date creationDate, Date updateDate, int updatedByUser) {
       this.activityNr = activityNr;
       this.serviceRequest = serviceRequest;
       this.workOrderNr = workOrderNr;
       this.unit = unit;
       this.notes = notes;
       this.pestsId = pestsId;
       this.activityStatus = activityStatus;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.updatedByUser = updatedByUser;
    }
   
    public int getActivityNr() {
        return this.activityNr;
    }
    
    public void setActivityNr(int activityNr) {
        this.activityNr = activityNr;
    }
    public ServiceRequest getServiceRequest() {
        return this.serviceRequest;
    }
    
    public void setServiceRequest(ServiceRequest serviceRequest) {
        this.serviceRequest = serviceRequest;
    }
    public String getWorkOrderNr() {
        return this.workOrderNr;
    }
    
    public void setWorkOrderNr(String workOrderNr) {
        this.workOrderNr = workOrderNr;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public int getPestsId() {
        return this.pestsId;
    }
    
    public void setPestsId(int pestsId) {
        this.pestsId = pestsId;
    }
    public String getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(String activityStatus) {
        this.activityStatus = activityStatus;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public int getUpdatedByUser() {
        return this.updatedByUser;
    }
    
    public void setUpdatedByUser(int updatedByUser) {
        this.updatedByUser = updatedByUser;
    }




}


