package com.mycompany.propco_maven_new;
// Generated 21-May-2017 5:38:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ServiceRequestActivities generated by hbm2java
 */
@Entity
@Table(name="serviceRequestActivities"
    ,catalog="PROPCO_Maven_new"
    , uniqueConstraints = @UniqueConstraint(columnNames="serviceReqNr") 
)
public class ServiceRequestActivities  implements java.io.Serializable {


     private int activityNr;
     private ServiceRequest serviceRequest;
     private String workOrderNr;
     private String unit;
     private String notes;
     private int pestsId;
     private String activityStatus;
     private Date creationDate;
     private Date updateDate;
     private int updatedByUser;

    public ServiceRequestActivities() {
    }

    public ServiceRequestActivities(int activityNr, ServiceRequest serviceRequest, String workOrderNr, String unit, String notes, int pestsId, String activityStatus, Date creationDate, Date updateDate, int updatedByUser) {
       this.activityNr = activityNr;
       this.serviceRequest = serviceRequest;
       this.workOrderNr = workOrderNr;
       this.unit = unit;
       this.notes = notes;
       this.pestsId = pestsId;
       this.activityStatus = activityStatus;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.updatedByUser = updatedByUser;
    }
   
     @Id 

    
    @Column(name="activityNr", unique=true, nullable=false)
    public int getActivityNr() {
        return this.activityNr;
    }
    
    public void setActivityNr(int activityNr) {
        this.activityNr = activityNr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="serviceReqNr", unique=true, nullable=false)
    public ServiceRequest getServiceRequest() {
        return this.serviceRequest;
    }
    
    public void setServiceRequest(ServiceRequest serviceRequest) {
        this.serviceRequest = serviceRequest;
    }

    
    @Column(name="workOrderNr", nullable=false, length=7)
    public String getWorkOrderNr() {
        return this.workOrderNr;
    }
    
    public void setWorkOrderNr(String workOrderNr) {
        this.workOrderNr = workOrderNr;
    }

    
    @Column(name="unit", nullable=false, length=10)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    
    @Column(name="notes", nullable=false, length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="pestsID", nullable=false)
    public int getPestsId() {
        return this.pestsId;
    }
    
    public void setPestsId(int pestsId) {
        this.pestsId = pestsId;
    }

    
    @Column(name="activityStatus", nullable=false, length=15)
    public String getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(String activityStatus) {
        this.activityStatus = activityStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creationDate", nullable=false, length=0)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updateDate", nullable=false, length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="updatedByUser", nullable=false)
    public int getUpdatedByUser() {
        return this.updatedByUser;
    }
    
    public void setUpdatedByUser(int updatedByUser) {
        this.updatedByUser = updatedByUser;
    }




}


