package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceRequest generated by hbm2java
 */
public class ServiceRequest  implements java.io.Serializable {


     private Integer serviceRequestNr;
     private Customer customer;
     private String purchaseOrderNumber;
     private String invoicing;
     private String serviceType;
     private String paymentType;
     private String schedule;
     private Date serviceDate;
     private Date creationDate;
     private Date updateDate;
     private int updatedByUser;
     private byte activityCount;
     private Set serviceRequestActivitieses = new HashSet(0);

    public ServiceRequest() {
    }

	
    public ServiceRequest(Customer customer, String invoicing, String serviceType, String paymentType, String schedule, Date serviceDate, Date creationDate, Date updateDate, int updatedByUser, byte activityCount) {
        this.customer = customer;
        this.invoicing = invoicing;
        this.serviceType = serviceType;
        this.paymentType = paymentType;
        this.schedule = schedule;
        this.serviceDate = serviceDate;
        this.creationDate = creationDate;
        this.updateDate = updateDate;
        this.updatedByUser = updatedByUser;
        this.activityCount = activityCount;
    }
    public ServiceRequest(Customer customer, String purchaseOrderNumber, String invoicing, String serviceType, String paymentType, String schedule, Date serviceDate, Date creationDate, Date updateDate, int updatedByUser, byte activityCount, Set serviceRequestActivitieses) {
       this.customer = customer;
       this.purchaseOrderNumber = purchaseOrderNumber;
       this.invoicing = invoicing;
       this.serviceType = serviceType;
       this.paymentType = paymentType;
       this.schedule = schedule;
       this.serviceDate = serviceDate;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.updatedByUser = updatedByUser;
       this.activityCount = activityCount;
       this.serviceRequestActivitieses = serviceRequestActivitieses;
    }
   
    public Integer getServiceRequestNr() {
        return this.serviceRequestNr;
    }
    
    public void setServiceRequestNr(Integer serviceRequestNr) {
        this.serviceRequestNr = serviceRequestNr;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }
    
    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }
    public String getInvoicing() {
        return this.invoicing;
    }
    
    public void setInvoicing(String invoicing) {
        this.invoicing = invoicing;
    }
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public Date getServiceDate() {
        return this.serviceDate;
    }
    
    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public int getUpdatedByUser() {
        return this.updatedByUser;
    }
    
    public void setUpdatedByUser(int updatedByUser) {
        this.updatedByUser = updatedByUser;
    }
    public byte getActivityCount() {
        return this.activityCount;
    }
    
    public void setActivityCount(byte activityCount) {
        this.activityCount = activityCount;
    }
    public Set getServiceRequestActivitieses() {
        return this.serviceRequestActivitieses;
    }
    
    public void setServiceRequestActivitieses(Set serviceRequestActivitieses) {
        this.serviceRequestActivitieses = serviceRequestActivitieses;
    }




}


