package com.mycompany.propco_maven_new;
// Generated 21-May-2017 4:03:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String password;
     private boolean fullprivilege;
     private boolean serviceReceipt;
     private boolean assignServiceTech;
     private boolean pendingWo;
     private boolean reviewSr;
     private boolean invoices;
     private boolean reports;
     private Set customers = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String password, boolean fullprivilege, boolean serviceReceipt, boolean assignServiceTech, boolean pendingWo, boolean reviewSr, boolean invoices, boolean reports) {
        this.userName = userName;
        this.password = password;
        this.fullprivilege = fullprivilege;
        this.serviceReceipt = serviceReceipt;
        this.assignServiceTech = assignServiceTech;
        this.pendingWo = pendingWo;
        this.reviewSr = reviewSr;
        this.invoices = invoices;
        this.reports = reports;
    }
    public Users(String userName, String password, boolean fullprivilege, boolean serviceReceipt, boolean assignServiceTech, boolean pendingWo, boolean reviewSr, boolean invoices, boolean reports, Set customers) {
       this.userName = userName;
       this.password = password;
       this.fullprivilege = fullprivilege;
       this.serviceReceipt = serviceReceipt;
       this.assignServiceTech = assignServiceTech;
       this.pendingWo = pendingWo;
       this.reviewSr = reviewSr;
       this.invoices = invoices;
       this.reports = reports;
       this.customers = customers;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isFullprivilege() {
        return this.fullprivilege;
    }
    
    public void setFullprivilege(boolean fullprivilege) {
        this.fullprivilege = fullprivilege;
    }
    public boolean isServiceReceipt() {
        return this.serviceReceipt;
    }
    
    public void setServiceReceipt(boolean serviceReceipt) {
        this.serviceReceipt = serviceReceipt;
    }
    public boolean isAssignServiceTech() {
        return this.assignServiceTech;
    }
    
    public void setAssignServiceTech(boolean assignServiceTech) {
        this.assignServiceTech = assignServiceTech;
    }
    public boolean isPendingWo() {
        return this.pendingWo;
    }
    
    public void setPendingWo(boolean pendingWo) {
        this.pendingWo = pendingWo;
    }
    public boolean isReviewSr() {
        return this.reviewSr;
    }
    
    public void setReviewSr(boolean reviewSr) {
        this.reviewSr = reviewSr;
    }
    public boolean isInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(boolean invoices) {
        this.invoices = invoices;
    }
    public boolean isReports() {
        return this.reports;
    }
    
    public void setReports(boolean reports) {
        this.reports = reports;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


