package com.mycompany.propco_maven_new;
// Generated 21-May-2017 5:38:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="PROPCO_Maven_new"
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String password;
     private boolean fullprivilege;
     private boolean serviceReceipt;
     private boolean assignServiceTech;
     private boolean pendingWo;
     private boolean reviewSr;
     private boolean invoices;
     private boolean reports;
     private Set customers = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String password, boolean fullprivilege, boolean serviceReceipt, boolean assignServiceTech, boolean pendingWo, boolean reviewSr, boolean invoices, boolean reports) {
        this.userName = userName;
        this.password = password;
        this.fullprivilege = fullprivilege;
        this.serviceReceipt = serviceReceipt;
        this.assignServiceTech = assignServiceTech;
        this.pendingWo = pendingWo;
        this.reviewSr = reviewSr;
        this.invoices = invoices;
        this.reports = reports;
    }
    public Users(String userName, String password, boolean fullprivilege, boolean serviceReceipt, boolean assignServiceTech, boolean pendingWo, boolean reviewSr, boolean invoices, boolean reports, Set customers) {
       this.userName = userName;
       this.password = password;
       this.fullprivilege = fullprivilege;
       this.serviceReceipt = serviceReceipt;
       this.assignServiceTech = assignServiceTech;
       this.pendingWo = pendingWo;
       this.reviewSr = reviewSr;
       this.invoices = invoices;
       this.reports = reports;
       this.customers = customers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userID", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="userName", nullable=false, length=12)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=8)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="fullprivilege", nullable=false)
    public boolean isFullprivilege() {
        return this.fullprivilege;
    }
    
    public void setFullprivilege(boolean fullprivilege) {
        this.fullprivilege = fullprivilege;
    }

    
    @Column(name="ServiceReceipt", nullable=false)
    public boolean isServiceReceipt() {
        return this.serviceReceipt;
    }
    
    public void setServiceReceipt(boolean serviceReceipt) {
        this.serviceReceipt = serviceReceipt;
    }

    
    @Column(name="AssignServiceTech", nullable=false)
    public boolean isAssignServiceTech() {
        return this.assignServiceTech;
    }
    
    public void setAssignServiceTech(boolean assignServiceTech) {
        this.assignServiceTech = assignServiceTech;
    }

    
    @Column(name="PendingWO", nullable=false)
    public boolean isPendingWo() {
        return this.pendingWo;
    }
    
    public void setPendingWo(boolean pendingWo) {
        this.pendingWo = pendingWo;
    }

    
    @Column(name="ReviewSR", nullable=false)
    public boolean isReviewSr() {
        return this.reviewSr;
    }
    
    public void setReviewSr(boolean reviewSr) {
        this.reviewSr = reviewSr;
    }

    
    @Column(name="Invoices", nullable=false)
    public boolean isInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(boolean invoices) {
        this.invoices = invoices;
    }

    
    @Column(name="Reports", nullable=false)
    public boolean isReports() {
        return this.reports;
    }
    
    public void setReports(boolean reports) {
        this.reports = reports;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


