package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bundles generated by hbm2java
 */
public class Bundles  implements java.io.Serializable {


     private int bdlid;
     private Business business;
     private String bundleName;
     private Set serviceRequests = new HashSet(0);
     private Set customers = new HashSet(0);

    public Bundles() {
    }

    public Bundles(String bundleName) {
        this.bundleName = bundleName;
    }
	
    public Bundles(int bdlid, Business business, String bundleName) {
        this.bdlid = bdlid;
        this.business = business;
        this.bundleName = bundleName;
    }
    public Bundles(int bdlid, Business business, String bundleName, Set serviceRequests, Set customers) {
       this.bdlid = bdlid;
       this.business = business;
       this.bundleName = bundleName;
       this.serviceRequests = serviceRequests;
       this.customers = customers;
    }
   
    public int getBdlid() {
        return this.bdlid;
    }
    
    public void setBdlid(int bdlid) {
        this.bdlid = bdlid;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public String getBundleName() {
        return this.bundleName;
    }
    
    public void setBundleName(String bundleName) {
        this.bundleName = bundleName;
    }
    public Set getServiceRequests() {
        return this.serviceRequests;
    }
    
    public void setServiceRequests(Set serviceRequests) {
        this.serviceRequests = serviceRequests;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


