package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Business generated by hbm2java
 */
public class Business  implements java.io.Serializable {


     private Short bid;
     private Users users;
     private String name;
     private String alias;
     private String address;
     private String city;
     private String province;
     private String postalCode;
     private String contactName;
     private String primaryPhone;
     private String ext;
     private String secondaryPhone;
     private String ext2;
     private String fax;
     private String emailAddress;
     private String tax;
     private String taxRate;
     private Date creationDate;
     private Date updateDate;
     private Set serviceRequests = new HashSet(0);
     private Set bundleses = new HashSet(0);
     private Set customers = new HashSet(0);
     private Set departments = new HashSet(0);

    public Business() {
    }

	
    public Business(Users users, String name, String alias, String address, String city, String province, String postalCode, String contactName, String primaryPhone, String ext, String secondaryPhone, String ext2, String fax, String emailAddress, String tax, String taxRate, Date creationDate, Date updateDate) {
        this.users = users;
        this.name = name;
        this.alias = alias;
        this.address = address;
        this.city = city;
        this.province = province;
        this.postalCode = postalCode;
        this.contactName = contactName;
        this.primaryPhone = primaryPhone;
        this.ext = ext;
        this.secondaryPhone = secondaryPhone;
        this.ext2 = ext2;
        this.fax = fax;
        this.emailAddress = emailAddress;
        this.tax = tax;
        this.taxRate = taxRate;
        this.creationDate = creationDate;
        this.updateDate = updateDate;
    }
    public Business(Users users, String name, String alias, String address, String city, String province, String postalCode, String contactName, String primaryPhone, String ext, String secondaryPhone, String ext2, String fax, String emailAddress, String tax, String taxRate, Date creationDate, Date updateDate, Set serviceRequests, Set bundleses, Set customers, Set departments) {
       this.users = users;
       this.name = name;
       this.alias = alias;
       this.address = address;
       this.city = city;
       this.province = province;
       this.postalCode = postalCode;
       this.contactName = contactName;
       this.primaryPhone = primaryPhone;
       this.ext = ext;
       this.secondaryPhone = secondaryPhone;
       this.ext2 = ext2;
       this.fax = fax;
       this.emailAddress = emailAddress;
       this.tax = tax;
       this.taxRate = taxRate;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.serviceRequests = serviceRequests;
       this.bundleses = bundleses;
       this.customers = customers;
       this.departments = departments;
    }
   
    public Short getBid() {
        return this.bid;
    }
    
    public void setBid(Short bid) {
        this.bid = bid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getPrimaryPhone() {
        return this.primaryPhone;
    }
    
    public void setPrimaryPhone(String primaryPhone) {
        this.primaryPhone = primaryPhone;
    }
    public String getExt() {
        return this.ext;
    }
    
    public void setExt(String ext) {
        this.ext = ext;
    }
    public String getSecondaryPhone() {
        return this.secondaryPhone;
    }
    
    public void setSecondaryPhone(String secondaryPhone) {
        this.secondaryPhone = secondaryPhone;
    }
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getTax() {
        return this.tax;
    }
    
    public void setTax(String tax) {
        this.tax = tax;
    }
    public String getTaxRate() {
        return this.taxRate;
    }
    
    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Set getServiceRequests() {
        return this.serviceRequests;
    }
    
    public void setServiceRequests(Set serviceRequests) {
        this.serviceRequests = serviceRequests;
    }
    public Set getBundleses() {
        return this.bundleses;
    }
    
    public void setBundleses(Set bundleses) {
        this.bundleses = bundleses;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }




}


