package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer cid;
     private Bundles bundles;
     private Business business;
     private Department department;
     private Users users;
     private String customerName;
     private String notes;
     private String address;
     private String addressNotes;
     private String city;
     private String province;
     private String postalCode;
     private String contactName;
     private String primaryPhone;
     private String ext;
     private String secondaryPhone;
     private String ext2;
     private String other;
     private String fax;
     private String emailAddress;
     private String contractNr;
     private Date creationDate;
     private Date updateDate;
     private Set serviceRequests = new HashSet(0);

    public Customer() {
    }

	
    public Customer(Business business, Department department, Users users, String customerName, String notes, String address, String addressNotes, String city, String province, String postalCode, String contactName, String primaryPhone, String ext, String secondaryPhone, String ext2, String other, String fax, String emailAddress, String contractNr, Date creationDate, Date updateDate) {
        this.business = business;
        this.department = department;
        this.users = users;
        this.customerName = customerName;
        this.notes = notes;
        this.address = address;
        this.addressNotes = addressNotes;
        this.city = city;
        this.province = province;
        this.postalCode = postalCode;
        this.contactName = contactName;
        this.primaryPhone = primaryPhone;
        this.ext = ext;
        this.secondaryPhone = secondaryPhone;
        this.ext2 = ext2;
        this.other = other;
        this.fax = fax;
        this.emailAddress = emailAddress;
        this.contractNr = contractNr;
        this.creationDate = creationDate;
        this.updateDate = updateDate;
    }
    public Customer(Bundles bundles, Business business, Department department, Users users, String customerName, String notes, String address, String addressNotes, String city, String province, String postalCode, String contactName, String primaryPhone, String ext, String secondaryPhone, String ext2, String other, String fax, String emailAddress, String contractNr, Date creationDate, Date updateDate, Set serviceRequests) {
       this.bundles = bundles;
       this.business = business;
       this.department = department;
       this.users = users;
       this.customerName = customerName;
       this.notes = notes;
       this.address = address;
       this.addressNotes = addressNotes;
       this.city = city;
       this.province = province;
       this.postalCode = postalCode;
       this.contactName = contactName;
       this.primaryPhone = primaryPhone;
       this.ext = ext;
       this.secondaryPhone = secondaryPhone;
       this.ext2 = ext2;
       this.other = other;
       this.fax = fax;
       this.emailAddress = emailAddress;
       this.contractNr = contractNr;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.serviceRequests = serviceRequests;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Bundles getBundles() {
        return this.bundles;
    }
    
    public void setBundles(Bundles bundles) {
        this.bundles = bundles;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddressNotes() {
        return this.addressNotes;
    }
    
    public void setAddressNotes(String addressNotes) {
        this.addressNotes = addressNotes;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getPrimaryPhone() {
        return this.primaryPhone;
    }
    
    public void setPrimaryPhone(String primaryPhone) {
        this.primaryPhone = primaryPhone;
    }
    public String getExt() {
        return this.ext;
    }
    
    public void setExt(String ext) {
        this.ext = ext;
    }
    public String getSecondaryPhone() {
        return this.secondaryPhone;
    }
    
    public void setSecondaryPhone(String secondaryPhone) {
        this.secondaryPhone = secondaryPhone;
    }
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getContractNr() {
        return this.contractNr;
    }
    
    public void setContractNr(String contractNr) {
        this.contractNr = contractNr;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Set getServiceRequests() {
        return this.serviceRequests;
    }
    
    public void setServiceRequests(Set serviceRequests) {
        this.serviceRequests = serviceRequests;
    }




}


