package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1



/**
 * HouseKeeping generated by hbm2java
 */
public class HouseKeeping  implements java.io.Serializable {


     private String hkType;
     private String description;

    public HouseKeeping() {
    }

    public HouseKeeping(String hkType, String description) {
       this.hkType = hkType;
       this.description = description;
    }
   
    public String getHkType() {
        return this.hkType;
    }
    
    public void setHkType(String hkType) {
        this.hkType = hkType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


