package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1



/**
 * Pests generated by hbm2java
 */
public class Pests  implements java.io.Serializable {


     private short pestsId;
     private String pestsType;

    public Pests() {
    }

    public Pests(short pestsId, String pestsType) {
       this.pestsId = pestsId;
       this.pestsType = pestsType;
    }
   
    public short getPestsId() {
        return this.pestsId;
    }
    
    public void setPestsId(short pestsId) {
        this.pestsId = pestsId;
    }
    public String getPestsType() {
        return this.pestsType;
    }
    
    public void setPestsType(String pestsType) {
        this.pestsType = pestsType;
    }




}


