package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Byte id;
     private String productName;
     private String measurement;
     private String pcpNumber;

    public Product() {
    }

    public Product(String productName, String measurement, String pcpNumber) {
       this.productName = productName;
       this.measurement = measurement;
       this.pcpNumber = pcpNumber;
    }
   
    public Byte getId() {
        return this.id;
    }
    
    public void setId(Byte id) {
        this.id = id;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getMeasurement() {
        return this.measurement;
    }
    
    public void setMeasurement(String measurement) {
        this.measurement = measurement;
    }
    public String getPcpNumber() {
        return this.pcpNumber;
    }
    
    public void setPcpNumber(String pcpNumber) {
        this.pcpNumber = pcpNumber;
    }




}


