package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ServiceRequestActivities generated by hbm2java
 */
public class ServiceRequestActivities  implements java.io.Serializable {


     private int serviceReqNr;
     private ServiceRequest serviceRequest;
     private int activityNr;
     private String wonr;
     private String unit;
     private String notes;
     private short pestsId;
     private String activityStatus;
     private Date creationDate;
     private Date updateDate;
     private byte uid;

    public ServiceRequestActivities() {
    }

    public ServiceRequestActivities(ServiceRequest serviceRequest, int activityNr, String wonr, String unit, String notes, short pestsId, String activityStatus, Date creationDate, Date updateDate, byte uid) {
       this.serviceRequest = serviceRequest;
       this.activityNr = activityNr;
       this.wonr = wonr;
       this.unit = unit;
       this.notes = notes;
       this.pestsId = pestsId;
       this.activityStatus = activityStatus;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.uid = uid;
    }
   
    public int getServiceReqNr() {
        return this.serviceReqNr;
    }
    
    public void setServiceReqNr(int serviceReqNr) {
        this.serviceReqNr = serviceReqNr;
    }
    public ServiceRequest getServiceRequest() {
        return this.serviceRequest;
    }
    
    public void setServiceRequest(ServiceRequest serviceRequest) {
        this.serviceRequest = serviceRequest;
    }
    public int getActivityNr() {
        return this.activityNr;
    }
    
    public void setActivityNr(int activityNr) {
        this.activityNr = activityNr;
    }
    public String getWonr() {
        return this.wonr;
    }
    
    public void setWonr(String wonr) {
        this.wonr = wonr;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public short getPestsId() {
        return this.pestsId;
    }
    
    public void setPestsId(short pestsId) {
        this.pestsId = pestsId;
    }
    public String getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(String activityStatus) {
        this.activityStatus = activityStatus;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public byte getUid() {
        return this.uid;
    }
    
    public void setUid(byte uid) {
        this.uid = uid;
    }




}


