package com.mycompany.propco_maven;
// Generated 10-May-2017 9:39:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Byte uid;
     private String userName;
     private String password;
     private boolean fullPrivilege;
     private boolean serviceReceipt;
     private boolean assignServiceTech;
     private boolean pendingWo;
     private boolean reviewSr;
     private boolean invoices;
     private boolean reports;
     private Set serviceRequests = new HashSet(0);
     private Set businesses = new HashSet(0);
     private Set departments = new HashSet(0);
     private Set customers = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String password, boolean fullPrivilege, boolean serviceReceipt, boolean assignServiceTech, boolean pendingWo, boolean reviewSr, boolean invoices, boolean reports) {
        this.userName = userName;
        this.password = password;
        this.fullPrivilege = fullPrivilege;
        this.serviceReceipt = serviceReceipt;
        this.assignServiceTech = assignServiceTech;
        this.pendingWo = pendingWo;
        this.reviewSr = reviewSr;
        this.invoices = invoices;
        this.reports = reports;
    }
    public Users(String userName, String password, boolean fullPrivilege, boolean serviceReceipt, boolean assignServiceTech, boolean pendingWo, boolean reviewSr, boolean invoices, boolean reports, Set serviceRequests, Set businesses, Set departments, Set customers) {
       this.userName = userName;
       this.password = password;
       this.fullPrivilege = fullPrivilege;
       this.serviceReceipt = serviceReceipt;
       this.assignServiceTech = assignServiceTech;
       this.pendingWo = pendingWo;
       this.reviewSr = reviewSr;
       this.invoices = invoices;
       this.reports = reports;
       this.serviceRequests = serviceRequests;
       this.businesses = businesses;
       this.departments = departments;
       this.customers = customers;
    }
   
    public Byte getUid() {
        return this.uid;
    }
    
    public void setUid(Byte uid) {
        this.uid = uid;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isFullPrivilege() {
        return this.fullPrivilege;
    }
    
    public void setFullPrivilege(boolean fullPrivilege) {
        this.fullPrivilege = fullPrivilege;
    }
    public boolean isServiceReceipt() {
        return this.serviceReceipt;
    }
    
    public void setServiceReceipt(boolean serviceReceipt) {
        this.serviceReceipt = serviceReceipt;
    }
    public boolean isAssignServiceTech() {
        return this.assignServiceTech;
    }
    
    public void setAssignServiceTech(boolean assignServiceTech) {
        this.assignServiceTech = assignServiceTech;
    }
    public boolean isPendingWo() {
        return this.pendingWo;
    }
    
    public void setPendingWo(boolean pendingWo) {
        this.pendingWo = pendingWo;
    }
    public boolean isReviewSr() {
        return this.reviewSr;
    }
    
    public void setReviewSr(boolean reviewSr) {
        this.reviewSr = reviewSr;
    }
    public boolean isInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(boolean invoices) {
        this.invoices = invoices;
    }
    public boolean isReports() {
        return this.reports;
    }
    
    public void setReports(boolean reports) {
        this.reports = reports;
    }
    public Set getServiceRequests() {
        return this.serviceRequests;
    }
    
    public void setServiceRequests(Set serviceRequests) {
        this.serviceRequests = serviceRequests;
    }
    public Set getBusinesses() {
        return this.businesses;
    }
    
    public void setBusinesses(Set businesses) {
        this.businesses = businesses;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


